name: Update Markdown and Commit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 0' # Runs at 6:00 AM UTC every Sunday

jobs:
  update-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m venv env
        source env/bin/activate
        pip install -r requirements.txt

    - name: Run update script
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        source env/bin/activate
        python contributions.py

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

    - name: Check for changes and commit if any
      id: git_status
      run: |
        git add _pages/opensource-projects.md
        if git diff-index --quiet HEAD; then
          echo "No changes to commit"
          echo "::set-output name=changes::false"
        else
          echo "::set-output name=changes::true"
        fi

    - name: Commit changes
      if: steps.git_status.outputs.changes == 'true'
      run: |
        git commit -m "Update open source project page of contributions file"
    
    - name: Push changes
      if: steps.git_status.outputs.changes == 'true'
      env:
        GH_PAT: ${{ secrets.ACCESS_TOKEN }}
      run: |
        git remote set-url origin https://x-access-token:${GH_PAT}@github.com/sqali/sqali.github.io.git
        git push origin job
